/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author Luiz Torres
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mArquivo = new javax.swing.JMenu();
        miDeslogar = new javax.swing.JMenuItem();
        miSair = new javax.swing.JMenuItem();
        mFun = new javax.swing.JMenu();
        miCadFu = new javax.swing.JMenuItem();
        miAtuFu = new javax.swing.JMenuItem();
        miExFun = new javax.swing.JMenuItem();
        miPesqFun = new javax.swing.JMenuItem();
        mClientes = new javax.swing.JMenu();
        miCadClientes = new javax.swing.JMenuItem();
        miAtuClientes = new javax.swing.JMenuItem();
        miExClientes = new javax.swing.JMenuItem();
        miPesqClientes = new javax.swing.JMenuItem();
        mFinan = new javax.swing.JMenu();
        mService = new javax.swing.JMenu();
        miCadService = new javax.swing.JMenuItem();
        miPesqService = new javax.swing.JMenuItem();
        mEstoque = new javax.swing.JMenu();
        miProdutos = new javax.swing.JMenuItem();
        mAgenda = new javax.swing.JMenu();
        miAgendar = new javax.swing.JMenuItem();
        miPesqAgenda = new javax.swing.JMenuItem();
        mConfig = new javax.swing.JMenu();
        mSobre = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BARBERSHOP --- Principal");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/view/images/asterisk_yellow.png")).getImage());

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 838, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );

        mArquivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/page.png"))); // NOI18N
        mArquivo.setText("Arquivo");

        miDeslogar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/key.png"))); // NOI18N
        miDeslogar.setText("Deslogar");
        miDeslogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miDeslogarActionPerformed(evt);
            }
        });
        mArquivo.add(miDeslogar);

        miSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/door_out.png"))); // NOI18N
        miSair.setText("Sair");
        miSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSairActionPerformed(evt);
            }
        });
        mArquivo.add(miSair);

        jMenuBar1.add(mArquivo);

        mFun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/user.png"))); // NOI18N
        mFun.setText("Funcionarios");

        miCadFu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/user_add.png"))); // NOI18N
        miCadFu.setText("Cadastrar");
        miCadFu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadFuActionPerformed(evt);
            }
        });
        mFun.add(miCadFu);

        miAtuFu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/user_edit.png"))); // NOI18N
        miAtuFu.setText("Atualizar");
        mFun.add(miAtuFu);

        miExFun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/user_delete.png"))); // NOI18N
        miExFun.setText("Excluir");
        mFun.add(miExFun);

        miPesqFun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/zoom.png"))); // NOI18N
        miPesqFun.setText("Pesquisar");
        miPesqFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPesqFunActionPerformed(evt);
            }
        });
        mFun.add(miPesqFun);

        jMenuBar1.add(mFun);

        mClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/group.png"))); // NOI18N
        mClientes.setText("Clientes");

        miCadClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/group_add.png"))); // NOI18N
        miCadClientes.setText("Cadastrar");
        miCadClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadClientesActionPerformed(evt);
            }
        });
        mClientes.add(miCadClientes);

        miAtuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/group_edit.png"))); // NOI18N
        miAtuClientes.setText("Atualizar");
        mClientes.add(miAtuClientes);

        miExClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/group_delete.png"))); // NOI18N
        miExClientes.setText("Excluir");
        mClientes.add(miExClientes);

        miPesqClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/zoom.png"))); // NOI18N
        miPesqClientes.setText("Pesquisar");
        miPesqClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPesqClientesActionPerformed(evt);
            }
        });
        mClientes.add(miPesqClientes);

        jMenuBar1.add(mClientes);

        mFinan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/money_dollar.png"))); // NOI18N
        mFinan.setText("Financeiro");
        mFinan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mFinanMouseClicked(evt);
            }
        });
        jMenuBar1.add(mFinan);

        mService.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/table.png"))); // NOI18N
        mService.setText("Serviços");

        miCadService.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/table_add.png"))); // NOI18N
        miCadService.setText("Cadastrar");
        miCadService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadServiceActionPerformed(evt);
            }
        });
        mService.add(miCadService);

        miPesqService.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/zoom.png"))); // NOI18N
        miPesqService.setText("Pesquisar");
        mService.add(miPesqService);

        mEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/cart.png"))); // NOI18N
        mEstoque.setText("Estoque");

        miProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/cart_add.png"))); // NOI18N
        miProdutos.setText("Produtos");
        miProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miProdutosActionPerformed(evt);
            }
        });
        mEstoque.add(miProdutos);

        mService.add(mEstoque);

        jMenuBar1.add(mService);

        mAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/calendar.png"))); // NOI18N
        mAgenda.setText("Agendamentos");

        miAgendar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/calendar_add.png"))); // NOI18N
        miAgendar.setText("Agendar");
        miAgendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAgendarActionPerformed(evt);
            }
        });
        mAgenda.add(miAgendar);

        miPesqAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/zoom.png"))); // NOI18N
        miPesqAgenda.setText("Pesquisar");
        mAgenda.add(miPesqAgenda);

        jMenuBar1.add(mAgenda);

        mConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/cog.png"))); // NOI18N
        mConfig.setText("Configurações");
        jMenuBar1.add(mConfig);

        mSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/information.png"))); // NOI18N
        mSobre.setText("Sobre");
        mSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mSobreMouseClicked(evt);
            }
        });
        jMenuBar1.add(mSobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mSobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mSobreMouseClicked
        // TODO add your handling code here:

        JOptionPane.showMessageDialog(null, "\n\n Criado por Luiz Torres em \n 19 de Setembro de 2019 \n\n Ver.1.0.0\n\n");

    }//GEN-LAST:event_mSobreMouseClicked

    private void miSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_miSairActionPerformed

    private void miCadFuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadFuActionPerformed
        // TODO add your handling code here:
        TelaCadastroFun cadastro = new TelaCadastroFun(this, false);
        cadastro.setVisible(true);

    }//GEN-LAST:event_miCadFuActionPerformed

    private void miDeslogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDeslogarActionPerformed
        // TODO add your handling code here:
        new TelaLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_miDeslogarActionPerformed

    private void miCadClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadClientesActionPerformed
        // TODO add your handling code here:
        TelaCadClientes cadastroC = new TelaCadClientes(this, false);
        cadastroC.setVisible(true);

    }//GEN-LAST:event_miCadClientesActionPerformed

    private void miPesqFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPesqFunActionPerformed
        // TODO add your handling code here:
        TelaPesqFun pesquisa = new TelaPesqFun(this, false);
        pesquisa.setVisible(true);
    }//GEN-LAST:event_miPesqFunActionPerformed

    private void miPesqClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPesqClientesActionPerformed
        // TODO add your handling code here:
        TelaPesqClientes pesquisa = new TelaPesqClientes(this, false);
        pesquisa.setVisible(true);
    }//GEN-LAST:event_miPesqClientesActionPerformed

    private void mFinanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mFinanMouseClicked
        // TODO add your handling code here:
        TelaFinanceiro financeiro = new TelaFinanceiro(this, false);
        financeiro.setVisible(true);
    }//GEN-LAST:event_mFinanMouseClicked

    private void miAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAgendarActionPerformed
        // TODO add your handling code here:
        TelaAgendamentos agendar = new TelaAgendamentos(this, false);
        agendar.setVisible(true);
    }//GEN-LAST:event_miAgendarActionPerformed

    private void miProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miProdutosActionPerformed
        // TODO add your handling code here:
        TelaProduto produto = new TelaProduto(this, false);
        produto.setVisible(true);
    }//GEN-LAST:event_miProdutosActionPerformed

    private void miCadServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadServiceActionPerformed
        // TODO add your handling code here:
        TelaCadServicos cadservico = new TelaCadServicos(this, false);
        cadservico.setVisible(true);
    }//GEN-LAST:event_miCadServiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mAgenda;
    private javax.swing.JMenu mArquivo;
    private javax.swing.JMenu mClientes;
    private javax.swing.JMenu mConfig;
    private javax.swing.JMenu mEstoque;
    private javax.swing.JMenu mFinan;
    private javax.swing.JMenu mFun;
    private javax.swing.JMenu mService;
    private javax.swing.JMenu mSobre;
    private javax.swing.JMenuItem miAgendar;
    private javax.swing.JMenuItem miAtuClientes;
    private javax.swing.JMenuItem miAtuFu;
    private javax.swing.JMenuItem miCadClientes;
    private javax.swing.JMenuItem miCadFu;
    private javax.swing.JMenuItem miCadService;
    private javax.swing.JMenuItem miDeslogar;
    private javax.swing.JMenuItem miExClientes;
    private javax.swing.JMenuItem miExFun;
    private javax.swing.JMenuItem miPesqAgenda;
    private javax.swing.JMenuItem miPesqClientes;
    private javax.swing.JMenuItem miPesqFun;
    private javax.swing.JMenuItem miPesqService;
    private javax.swing.JMenuItem miProdutos;
    private javax.swing.JMenuItem miSair;
    // End of variables declaration//GEN-END:variables
}
